package dev.yorkie.document.time

/**
 * [ActorID] is used to identify who is making changes to the document.
 * It is hexadecimal string and should be generated by unique value.
 */
@JvmInline
internal value class ActorID(val id: String) : Comparable<ActorID> {

    override fun compareTo(other: ActorID): Int {
        return id.compareTo(other.id)
    }

    companion object {
        /**
         * [INITIAL_ACTOR_ID] is the initial value of ActorID.
         */
        val INITIAL_ACTOR_ID: ActorID = ActorID("000000000000000000000000")

        /**
         * [MAX_ACTOR_ID] is the maximum value of ActorID.
         */
        val MAX_ACTOR_ID: ActorID = ActorID("FFFFFFFFFFFFFFFFFFFFFFFF")
    }
}
