package dev.yorkie.document.time

/**
 * [ActorID] is used to identify who is making changes to the document.
 * It is a hexadecimal string and should be generated by a unique value.
 */
@JvmInline
public value class ActorID(val value: String) : Comparable<ActorID> {

    override fun compareTo(other: ActorID): Int {
        return value.compareTo(other.value)
    }

    companion object {
        /**
         * [INITIAL_ACTOR_ID] is the initial value of [ActorID].
         */
        val INITIAL_ACTOR_ID: ActorID = ActorID("000000000000000000000000")

        /**
         * [MAX_ACTOR_ID] is the maximum value of [ActorID].
         */
        val MAX_ACTOR_ID: ActorID = ActorID("ffffffffffffffffffffffff")
    }
}
