package com.google.protobuf

/**
 * Stub annotation for compatibility with code generated by the buf plugin.
 * The buf plugin generates @com.google.protobuf.Generated annotations.
 * This stub provides fallback support and is compatible with both Kotlin (@file annotation)
 * and Java (class annotation). The actual annotation is available in protobuf-java.
 */
@Target(
    AnnotationTarget.FILE,
    AnnotationTarget.CLASS,
    AnnotationTarget.ANNOTATION_CLASS,
    AnnotationTarget.FUNCTION,
    AnnotationTarget.PROPERTY,
    AnnotationTarget.FIELD,
)
@Retention(AnnotationRetention.SOURCE)
annotation class Generated
