version: '3.3'

services:
  yorkie:
    image: 'yorkieteam/yorkie:0.5.6'
    container_name: 'yorkie'
    restart: always
    ports:
      - '8080:8080'
      - '8081:8081'
    command: >
      server --enable-pprof --rpc-addr 0.0.0.0:8080
