services:
  yorkie:
    image: 'yorkieteam/yorkie:0.6.21'
    container_name: 'yorkie'
    restart: always
    ports:
      - '8080:8080'
      - '8081:8081'
    command: >
      server --pprof-enabled --rpc-addr 0.0.0.0:8080
