package dev.yorkie.document.operation

import dev.yorkie.document.crdt.CrdtRoot
import dev.yorkie.document.crdt.CrdtText
import dev.yorkie.document.crdt.RgaTreeSplitNodeID
import dev.yorkie.document.crdt.RgaTreeSplitPos
import dev.yorkie.document.crdt.RgaTreeSplitPosRange
import dev.yorkie.document.crdt.TextValue
import dev.yorkie.document.crdt.TextWithAttributes
import dev.yorkie.document.time.TimeTicket
import dev.yorkie.document.time.VersionVector
import dev.yorkie.util.Logger.Companion.logError

/**
 * [EditOperation] is an operations representing editing rich text.
 */
internal data class EditOperation(
    val fromPos: RgaTreeSplitPos,
    val toPos: RgaTreeSplitPos,
    val content: String,
    override var parentCreatedAt: TimeTicket,
    override var executedAt: TimeTicket,
    val attributes: Map<String, String>,
    /**
     * Document-index offsets that define the undo range in the integer coordinate space.
     * These are used by [reconcileOperation] to adjust positions when remote edits land.
     *
     * A value of [NOT_AN_UNDO_OP] means this operation is not from the undo/redo stack and
     * [fromPos]/[toPos] should be applied directly without any index-based translation.
     * These fields are intentionally NOT serialised to protobuf — they only live on the
     * local undo/redo stack and are regenerated on each undo/redo execution.
     */
    var undoFromOffset: Int = NOT_AN_UNDO_OP,
    var undoToOffset: Int = NOT_AN_UNDO_OP,
) : Operation() {

    /** Returns true when this operation was generated by the local undo/redo stack. */
    val isUndoOp: Boolean
        get() = undoFromOffset != NOT_AN_UNDO_OP

    /**
     * Returns the created time of the effected element.
     */
    override val effectedCreatedAt: TimeTicket
        get() = parentCreatedAt

    override fun execute(
        root: CrdtRoot,
        source: OpSource,
        versionVector: VersionVector?,
    ): ExecutionResult {
        val parentObject = root.findByCreatedAt(parentCreatedAt)
        return if (parentObject is CrdtText) {
            // For undo ops, compute the current positions from the stored integer offsets
            // so that reconcile adjustments are honoured.  For all other operations
            // (including deserialized undo ops whose offsets have been lost) use the
            // stored positions directly — they are always valid node-relative positions.
            val (actualFrom, actualTo) = if (isUndoOp) {
                parentObject.indexRangeToPosRange(undoFromOffset, undoToOffset)
            } else {
                fromPos to toPos
            }

            val result = parentObject.edit(
                RgaTreeSplitPosRange(actualFrom, actualTo),
                content,
                executedAt,
                attributes,
                versionVector,
            )

            root.acc(result.dataSize)

            result.gcPairs.forEach(root::registerGCPair)

            val opInfos = result.textChanges.map { (_, _, from, to, content, attributes) ->
                OperationInfo.EditOpInfo(
                    from,
                    to,
                    TextWithAttributes(content.orEmpty() to attributes.orEmpty()),
                    root.createPath(parentCreatedAt),
                )
            }

            // Reverse ops are only generated for local and undo/redo operations.
            // Remote applications (applyChanges) do not produce reverse ops.
            val reverseOps = if (source == OpSource.Local || source == OpSource.UndoRedo) {
                // fromIndex is the document index where this edit starts in the live text.
                // Use the opInfo value computed during the edit (before any insertion offset).
                val fromIndex = opInfos.filterIsInstance<OperationInfo.EditOpInfo>()
                    .firstOrNull()?.from ?: 0
                listOf(toReverseOperation(actualFrom, fromIndex, result.removedValues))
            } else {
                emptyList()
            }

            ExecutionResult(opInfos = opInfos, reverseOps = reverseOps)
        } else {
            if (parentObject == null) {
                logError(TAG, "fail to find $parentCreatedAt")
            }
            logError(TAG, "fail to execute, only Text can execute edit")
            ExecutionResult(opInfos = emptyList())
        }
    }

    /**
     * Builds the reverse [EditOperation] that undoes this operation.
     *
     * [actualFrom] is the node-relative position that was actually used as the range start
     * (already split-stable and valid for direct [findNodeWithSplit] use).
     *
     * The reverse operation:
     * - Deletes the content that was inserted by this operation (if any), referenced by the
     *   freshly-inserted node whose ID is [(executedAt, 0)].
     * - Re-inserts any content that was deleted by this operation.
     *
     * Both [fromPos] and [toPos] on the returned operation are node-relative positions and
     * can be used directly without position refinement.  The [undoFromOffset]/[undoToOffset]
     * fields capture the equivalent document-index range so that [reconcileOperation] can
     * adjust them when concurrent remote edits arrive.
     */
    private fun toReverseOperation(
        actualFrom: RgaTreeSplitPos,
        fromIndex: Int,
        removedValues: List<TextValue>,
    ): EditOperation {
        // The reverse "to" points to the end of whatever was inserted.
        // If nothing was inserted (pure deletion), fromPos == toPos.
        val reverseTo = if (content.isNotEmpty()) {
            RgaTreeSplitPos(RgaTreeSplitNodeID(executedAt, 0), content.length)
        } else {
            actualFrom
        }

        val reverseContent = removedValues.joinToString("") { it.content }

        val reverseAttributes = if (removedValues.size == 1) {
            removedValues[0].attributes
        } else {
            emptyMap()
        }

        // Capture the integer document-index range of the reverse operation so that
        // reconcileOperation can shift it when concurrent remote edits land.
        // fromIndex is the live-text position BEFORE the edit was applied (from opInfos),
        // which is reliable even after the edit tombstones the range.
        val reverseFromIndex = fromIndex
        val reverseToIndex = fromIndex + content.length

        return EditOperation(
            fromPos = actualFrom,
            toPos = reverseTo,
            content = reverseContent,
            parentCreatedAt = parentCreatedAt,
            executedAt = executedAt,
            attributes = reverseAttributes,
            undoFromOffset = reverseFromIndex,
            undoToOffset = reverseToIndex,
        )
    }

    /**
     * Adjusts [undoFromOffset] and [undoToOffset] to account for a concurrent remote edit
     * that arrived at [[remoteFrom], [remoteTo]) inserting [remoteContentLen] characters.
     *
     * Six overlap cases (matching the JS implementation):
     * - Remote is entirely left of undo range → shift both endpoints right.
     * - Remote is entirely right of undo range → no change.
     * - Undo range is contained by remote → collapse to a point at remoteFrom.
     * - Remote is contained by undo range → expand toPos by content delta.
     * - Remote overlaps the start of undo range → shift fromPos right.
     * - Remote overlaps the end of undo range → truncate toPos.
     *
     * No-ops when [isUndoOp] is false (offsets are not set).
     */
    internal fun reconcileOperation(
        remoteFrom: Int,
        remoteTo: Int,
        remoteContentLen: Int,
    ) {
        if (!isUndoOp) return

        val undoFrom = undoFromOffset
        val undoTo = undoToOffset
        val remoteDelta = remoteContentLen - (remoteTo - remoteFrom)

        val newUndoFrom: Int
        val newUndoTo: Int

        when {
            // Case 2: remote is entirely right of undo range — no change.
            remoteFrom >= undoTo -> return
            // Case 1: remote is entirely left of undo range — shift both endpoints.
            remoteTo <= undoFrom -> {
                newUndoFrom = undoFrom + remoteDelta
                newUndoTo = undoTo + remoteDelta
            }
            // Case 3: undo range is contained by remote — collapse to a point.
            remoteFrom <= undoFrom && remoteTo >= undoTo -> {
                newUndoFrom = remoteFrom + remoteContentLen
                newUndoTo = remoteFrom + remoteContentLen
            }
            // Case 4: remote is contained by undo range — expand toPos only.
            remoteFrom > undoFrom && remoteTo < undoTo -> {
                newUndoFrom = undoFrom
                newUndoTo = undoTo + remoteDelta
            }
            // Case 5: remote overlaps the start of undo range.
            remoteFrom <= undoFrom -> {
                newUndoFrom = remoteFrom + remoteContentLen
                newUndoTo = undoTo + remoteDelta
            }
            // Case 6: remote overlaps the end of undo range.
            else -> {
                newUndoFrom = undoFrom
                newUndoTo = remoteFrom
            }
        }

        undoFromOffset = newUndoFrom
        undoToOffset = newUndoTo
    }

    companion object {
        private const val TAG = "EditOperation"
        internal const val NOT_AN_UNDO_OP = -1
    }
}
