package dev.yorkie.document.operation

import dev.yorkie.document.crdt.CrdtRoot
import dev.yorkie.document.crdt.CrdtText
import dev.yorkie.document.crdt.GCPair
import dev.yorkie.document.crdt.RestoreSpan
import dev.yorkie.document.crdt.RgaTreeSplitNodeID
import dev.yorkie.document.crdt.RgaTreeSplitPos
import dev.yorkie.document.crdt.RgaTreeSplitPosRange
import dev.yorkie.document.crdt.TextChange
import dev.yorkie.document.crdt.TextValue
import dev.yorkie.document.crdt.TextWithAttributes
import dev.yorkie.document.time.TimeTicket
import dev.yorkie.document.time.VersionVector
import dev.yorkie.util.DataSize
import dev.yorkie.util.Logger.Companion.logError
import dev.yorkie.util.addDataSizes

/**
 * [RestoreMode] selects the identity-preserving path for undo/redo of pure
 * deletions: [Restore] revives spans, [Retombstone] re-deletes them.
 */
internal enum class RestoreMode { Restore, Retombstone }

/**
 * [EditOperation] is an operations representing editing rich text.
 */
internal data class EditOperation(
    var fromPos: RgaTreeSplitPos,
    var toPos: RgaTreeSplitPos,
    val content: String,
    override var parentCreatedAt: TimeTicket,
    override var executedAt: TimeTicket,
    val attributes: Map<String, String>,
    /**
     * Document-index offsets that define the undo range in the integer coordinate space.
     * These are used by [reconcileOperation] to adjust positions when remote edits land.
     *
     * A value of [NOT_AN_UNDO_OP] means this operation is not from the undo/redo stack and
     * [fromPos]/[toPos] should be applied directly without any index-based translation.
     * These fields are intentionally NOT serialised to protobuf — they only live on the
     * local undo/redo stack and are regenerated on each undo/redo execution.
     */
    var undoFromOffset: Int = NOT_AN_UNDO_OP,
    var undoToOffset: Int = NOT_AN_UNDO_OP,
    /**
     * Identity-preserving restore payload (never populated for ordinary
     * edits). [restoreSpans] is content a reversed edit removed (to revive);
     * [retombstoneSpans] is content it inserted (to re-remove). Both are
     * addressed by original identity rather than copy-reinserted or
     * position-deleted, so a revived neighbour keeps its relative order
     * across chained undo/redo (and overlapping concurrent undos stay an
     * order-independent set union). [restoreMode] selects direction: null
     * means this is an ordinary edit.
     */
    val restoreSpans: List<RestoreSpan<TextValue>>? = null,
    val restoreMode: RestoreMode? = null,
    val retombstoneSpans: List<RestoreSpan<TextValue>>? = null,
) : Operation() {

    /** Returns true when this operation was generated by the local undo/redo stack. */
    val isUndoOp: Boolean
        get() = undoFromOffset != NOT_AN_UNDO_OP

    /** Returns true when this is an identity-preserving restore/retombstone operation. */
    val isRestoreOp: Boolean
        get() = restoreSpans != null || retombstoneSpans != null

    /**
     * Returns the created time of the effected element.
     */
    override val effectedCreatedAt: TimeTicket
        get() = parentCreatedAt

    override fun execute(
        root: CrdtRoot,
        source: OpSource,
        versionVector: VersionVector?,
    ): ExecutionResult {
        val parentObject = root.findByCreatedAt(parentCreatedAt)
        return if (parentObject is CrdtText) {
            // For undo ops, compute the current positions from the stored integer offsets
            // so that reconcile adjustments are honoured.  For all other operations
            // (including deserialized undo ops whose offsets have been lost) use the
            // stored positions directly — they are always valid node-relative positions.
            //
            // Restore/retombstone execution mutates content by identity rather than by
            // this op's own index range, so a chained undo/redo can leave undoFromOffset/
            // undoToOffset pointing past the live length (e.g. redoing an insert while the
            // doc is still shrunk from this same op's prior undo). Clamp both offsets to
            // the current length before resolving: actualTo is never read past this
            // resolution for a restore op, and actualFrom is only ever a last-resort
            // fallback anchor (DEC-5), so a clamped value is always safe.
            val (actualFrom, actualTo) = if (isUndoOp) {
                val length = parentObject.length
                parentObject.indexRangeToPosRange(
                    undoFromOffset.coerceIn(0, length),
                    undoToOffset.coerceIn(0, length),
                )
            } else {
                fromPos to toPos
            }

            if (isUndoOp) {
                fromPos = actualFrom
                toPos = actualTo
            }

            if (isRestoreOp) {
                return executeRestore(root, parentObject, source, actualFrom)
            }

            val result = parentObject.edit(
                RgaTreeSplitPosRange(actualFrom, actualTo),
                content,
                executedAt,
                attributes,
                versionVector,
            )

            root.acc(result.dataSize)

            result.gcPairs.forEach(root::registerGCPair)

            val opInfos = result.textChanges.map { (_, _, from, to, content, attributes) ->
                OperationInfo.EditOpInfo(
                    from,
                    to,
                    TextWithAttributes(content.orEmpty() to attributes.orEmpty()),
                    root.createPath(parentCreatedAt),
                )
            }

            // Reverse ops are only generated for local and undo/redo operations that
            // actually changed something. Remote applications (applyChanges) and
            // history-exempt (skipHistory) changes do not produce reverse ops, nor
            // does a zero-effect edit (empty opInfos).
            val reverseOps = if (opInfos.isNotEmpty() && source.producesReverseOps) {
                // fromIndex is the document index where this edit starts in the live text.
                // Use the opInfo value computed during the edit (before any insertion offset).
                val fromIndex = opInfos.filterIsInstance<OperationInfo.EditOpInfo>()
                    .firstOrNull()?.from ?: 0
                listOf(
                    toReverseOperation(
                        actualFrom,
                        fromIndex,
                        result.removedValues,
                        result.removedSpans,
                    ),
                )
            } else {
                emptyList()
            }

            ExecutionResult(opInfos = opInfos, reverseOps = reverseOps)
        } else {
            if (parentObject == null) {
                logError(TAG, "fail to find $parentCreatedAt")
            }
            logError(TAG, "fail to execute, only Text can execute edit")
            ExecutionResult(opInfos = emptyList())
        }
    }

    /**
     * Executes an identity-preserving restore/retombstone operation:
     * [restoreMode] picks the direction — [RestoreMode.Restore] revives
     * [restoreSpans] and re-removes [retombstoneSpans]; [RestoreMode.Retombstone]
     * (the redo) does the opposite. Both sets are revived/removed by their
     * original identity, never re-inserted as fresh nodes, so relative order
     * is preserved across chained undo/redo and overlapping concurrent undos
     * converge as an order-independent set union.
     *
     * [fallbackAnchor] is the reconciled `actualFrom` position computed by
     * [execute] — it doubles as the anchor [CrdtText.restore] falls back to
     * when a recreated span's neighbourhood has been fully purged (DEC-5).
     *
     * Order is load-bearing: (1) retombstone first — register its pairs and
     * collect opInfos; (2) restore — register its pending GC pairs BEFORE
     * unregistering the untombstoned nodes (a pending pair's node may be one
     * of the just-untombstoned nodes itself, so it must exist in the GC map
     * before being walked back out of it); (3) accumulate the total diff.
     */
    private fun executeRestore(
        root: CrdtRoot,
        text: CrdtText,
        source: OpSource,
        fallbackAnchor: RgaTreeSplitPos,
    ): ExecutionResult {
        val isRetombstone = restoreMode == RestoreMode.Retombstone
        val toRestore = (if (isRetombstone) retombstoneSpans else restoreSpans).orEmpty()
        val toRetombstone = (if (isRetombstone) restoreSpans else retombstoneSpans).orEmpty()

        val path = root.createPath(parentCreatedAt)
        fun List<TextChange>.toOpInfos() = map { (_, _, from, to, content, attributes) ->
            OperationInfo.EditOpInfo(
                from,
                to,
                TextWithAttributes(content.orEmpty() to attributes.orEmpty()),
                path,
            )
        }

        val opInfos = mutableListOf<OperationInfo>()
        var totalDiff = DataSize(data = 0, meta = 0)

        // 1. Remove the content the reversed edit inserted (by identity).
        if (toRetombstone.isNotEmpty()) {
            val result = text.retombstone(toRetombstone, executedAt)
            totalDiff = addDataSizes(totalDiff, result.dataSize)
            result.gcPairs.forEach(root::registerGCPair)
            opInfos += result.textChanges.toOpInfos()
        }

        // 2. Revive the content the reversed edit removed (by identity).
        if (toRestore.isNotEmpty()) {
            val result = text.restore(toRestore, executedAt, fallbackAnchor)
            result.pendingGcPairs.forEach(root::registerGCPair)
            result.untombstoned.forEach { node ->
                root.unregisterGCPair(GCPair(text.rgaTreeSplit, node))
            }
            totalDiff = addDataSizes(totalDiff, result.dataSize)
            opInfos += result.textChanges.toOpInfos()
        }

        root.acc(totalDiff)

        // Reverse ops are only generated for local and undo/redo operations
        // that actually changed something, mirroring the ordinary edit path
        // (restore()'s targets can already be live if a concurrent undo got
        // there first — see RgaTreeSplit.restore's idempotent-skip case —
        // in which case opInfos stays empty and there is nothing to reverse).
        val reverseOps = if (
            opInfos.isNotEmpty() &&
            (source == OpSource.Local || source == OpSource.UndoRedo)
        ) {
            // Keep the same span sets and undo offsets; flip only the mode.
            // undoFromOffset/undoToOffset need no re-derivation: they are
            // re-resolved into a position fresh on every execute() call via
            // indexRangeToPosRange, and History.reconcileTextEdit keeps them
            // tracking concurrent remote edits while this op sits on a stack.
            val flippedMode = if (isRetombstone) RestoreMode.Restore else RestoreMode.Retombstone
            listOf(copy(restoreMode = flippedMode))
        } else {
            emptyList()
        }

        return ExecutionResult(opInfos = opInfos, reverseOps = reverseOps)
    }

    /**
     * Builds the reverse [EditOperation] that undoes this operation.
     *
     * [actualFrom] is the node-relative position that was actually used as the range start
     * (already split-stable and valid for direct [findNodeWithSplit] use).
     *
     * When this edit removed and/or inserted content, the reverse is built by
     * IDENTITY rather than copy-reinsertion: it revives [removedSpans] (what
     * this edit removed) and re-removes an insertion span built from
     * [content] (what this edit inserted), both addressed by original
     * identity. A fresh copy-reinserted node sorts ahead of an as-yet-
     * unrevived neighbour and corrupts order across chained undo/redo (and
     * overlapping concurrent undos duplicate shared content); identity
     * addressing avoids both — see spec 004 Stage C / DEC-7.
     *
     * Both [fromPos] and [toPos] on the returned operation are node-relative positions and
     * can be used directly without position refinement.  The [undoFromOffset]/[undoToOffset]
     * fields capture the equivalent document-index range so that [reconcileOperation] can
     * adjust them when concurrent remote edits arrive.
     */
    private fun toReverseOperation(
        actualFrom: RgaTreeSplitPos,
        fromIndex: Int,
        removedValues: List<TextValue>,
        removedSpans: List<RestoreSpan<TextValue>>,
    ): EditOperation {
        // Capture the integer document-index range of the reverse operation so that
        // reconcileOperation can shift it when concurrent remote edits land.
        // fromIndex is the live-text position BEFORE the edit was applied (from opInfos),
        // which is reliable even after the edit tombstones the range.
        val reverseFromIndex = fromIndex
        val reverseToIndex = fromIndex + content.length

        if (removedSpans.isNotEmpty() || content.isNotEmpty()) {
            val insertedSpans = if (content.isNotEmpty()) {
                listOf(RestoreSpan(executedAt, 0, content.length, TextValue(content)))
            } else {
                null
            }
            return EditOperation(
                fromPos = actualFrom,
                toPos = actualFrom,
                content = "",
                parentCreatedAt = parentCreatedAt,
                executedAt = executedAt,
                attributes = emptyMap(),
                undoFromOffset = reverseFromIndex,
                undoToOffset = reverseToIndex,
                restoreSpans = removedSpans.ifEmpty { null },
                restoreMode = RestoreMode.Restore,
                retombstoneSpans = insertedSpans,
            )
        }

        // Nothing removed, nothing inserted (empty edge case): fall through
        // to the legacy copy-reinsert shape unchanged. In practice a pure
        // deletion always has removedSpans, so the identity branch above is
        // the one taken; this branch only covers a true no-op edit.
        val reverseTo = if (content.isNotEmpty()) {
            RgaTreeSplitPos(RgaTreeSplitNodeID(executedAt, 0), content.length)
        } else {
            actualFrom
        }

        val reverseContent = removedValues.joinToString("") { it.content }

        val reverseAttributes = if (removedValues.size == 1) {
            removedValues[0].attributes
        } else {
            emptyMap()
        }

        return EditOperation(
            fromPos = actualFrom,
            toPos = reverseTo,
            content = reverseContent,
            parentCreatedAt = parentCreatedAt,
            executedAt = executedAt,
            attributes = reverseAttributes,
            undoFromOffset = reverseFromIndex,
            undoToOffset = reverseToIndex,
        )
    }

    /**
     * Adjusts [undoFromOffset] and [undoToOffset] to account for a concurrent remote edit
     * that arrived at [[remoteFrom], [remoteTo]) inserting [remoteContentLen] characters.
     *
     * Six overlap cases (matching the JS implementation):
     * - Remote is entirely left of undo range → shift both endpoints right.
     * - Remote is entirely right of undo range → no change.
     * - Undo range is contained by remote → collapse to a point at remoteFrom.
     * - Remote is contained by undo range → expand toPos by content delta.
     * - Remote overlaps the start of undo range → shift fromPos right.
     * - Remote overlaps the end of undo range → truncate toPos.
     *
     * No-ops when [isUndoOp] is false (offsets are not set).
     *
     * Restore/retombstone ops address content by identity ([restoreSpans] /
     * [retombstoneSpans]), so [fromPos]/[toPos] are never used to locate the
     * restored range itself. But [undoFromOffset]/[undoToOffset] are also
     * resolved into [fromPos] at [execute] time as the fallback anchor for
     * when every related piece has been GC'd (DEC-5), so they still need to
     * track concurrent remote edits like any other undo position — this
     * method never reads the identity payload, so it needs no changes for
     * restore/retombstone ops.
     */
    internal fun reconcileOperation(
        remoteFrom: Int,
        remoteTo: Int,
        remoteContentLen: Int,
    ) {
        if (!isUndoOp) return

        val undoFrom = undoFromOffset
        val undoTo = undoToOffset
        val remoteDelta = remoteContentLen - (remoteTo - remoteFrom)

        val newUndoFrom: Int
        val newUndoTo: Int

        when {
            // Case 2: remote is entirely right of undo range — no change.
            remoteFrom >= undoTo -> return
            // Case 1: remote is entirely left of undo range — shift both endpoints.
            remoteTo <= undoFrom -> {
                newUndoFrom = undoFrom + remoteDelta
                newUndoTo = undoTo + remoteDelta
            }
            // Case 3: undo range is contained by remote — collapse to a point.
            remoteFrom <= undoFrom && remoteTo >= undoTo -> {
                newUndoFrom = remoteFrom + remoteContentLen
                newUndoTo = remoteFrom + remoteContentLen
            }
            // Case 4: remote is contained by undo range — expand toPos only.
            remoteFrom > undoFrom && remoteTo < undoTo -> {
                newUndoFrom = undoFrom
                newUndoTo = undoTo + remoteDelta
            }
            // Case 5: remote overlaps the start of undo range.
            remoteFrom <= undoFrom -> {
                newUndoFrom = remoteFrom + remoteContentLen
                newUndoTo = undoTo + remoteDelta
            }
            // Case 6: remote overlaps the end of undo range.
            else -> {
                newUndoFrom = undoFrom
                newUndoTo = remoteFrom
            }
        }

        undoFromOffset = newUndoFrom
        undoToOffset = newUndoTo
    }

    companion object {
        private const val TAG = "EditOperation"
        internal const val NOT_AN_UNDO_OP = -1
    }
}
