package dev.yorkie.document.operation

import dev.yorkie.document.crdt.CrdtRoot
import dev.yorkie.document.crdt.CrdtTree
import dev.yorkie.document.crdt.CrdtTreeNode
import dev.yorkie.document.crdt.CrdtTreeNode.Companion.CrdtTreeElement
import dev.yorkie.document.crdt.CrdtTreeNode.Companion.CrdtTreeText
import dev.yorkie.document.crdt.CrdtTreeNodeID
import dev.yorkie.document.crdt.CrdtTreePos
import dev.yorkie.document.crdt.Rht
import dev.yorkie.document.crdt.TreeElementNode
import dev.yorkie.document.crdt.TreeNode
import dev.yorkie.document.crdt.TreeTextNode
import dev.yorkie.document.crdt.toTreeNode
import dev.yorkie.document.time.TimeTicket
import dev.yorkie.document.time.VersionVector
import dev.yorkie.util.Logger.Companion.logError

/**
 * [TreeEditOperation] is an operation representing Tree editing.
 */
internal data class TreeEditOperation(
    override var parentCreatedAt: TimeTicket,
    val fromPos: CrdtTreePos,
    val toPos: CrdtTreePos,
    val contents: List<CrdtTreeNode>?,
    val splitLevel: Int,
    override var executedAt: TimeTicket,
    /**
     * Document-index offsets that define the undo range in the integer coordinate space.
     * These are used by [reconcileOperation] to adjust positions when remote edits land.
     *
     * A value of [NotAnUndoOp] means this operation is not from the undo/redo stack and
     * [fromPos]/[toPos] are applied directly without index-based translation.
     * These fields are intentionally NOT serialised to protobuf — they only live on the
     * local undo/redo stack and are regenerated on each undo/redo execution.
     */
    var undoFromOffset: Int = NotAnUndoOp,
    var undoToOffset: Int = NotAnUndoOp,
    /**
     * Logical snapshots of the nodes deleted by the original operation, stored as
     * plain [TreeNode] data (type/children/attributes only — no CRDT IDs). Used
     * exclusively on reverse/undo operations to rebuild the deleted subtrees with
     * fresh [CrdtTreeNodeID]s derived from the undo's [executedAt] ticket, avoiding
     * ID collisions with the already-tombstoned originals.
     *
     * Non-null only when [isUndoOp] is true and the original operation deleted content.
     * Not serialised to protobuf.
     */
    val removedNodeSnapshots: List<TreeNode>? = null,
    /**
     * Non-zero when this is a boundary-deletion op that was generated to undo a split.
     * Set so that its own reverse (the redo) regenerates a proper split instead of
     * re-inserting the tombstoned boundary nodes as raw content.
     * Not serialised to protobuf.
     */
    var redoSplitLevel: Int = 0,
) : Operation() {
    override val effectedCreatedAt = parentCreatedAt

    /** Returns true when this operation was generated by the local undo/redo stack. */
    val isUndoOp: Boolean
        get() = undoFromOffset != NotAnUndoOp

    override fun execute(
        root: CrdtRoot,
        source: OpSource,
        versionVector: VersionVector?,
    ): ExecutionResult {
        val tree = root.findByCreatedAt(parentCreatedAt)
        if (tree == null) {
            logError(TAG, "fail to find $parentCreatedAt")
            return ExecutionResult(opInfos = emptyList())
        }
        if (tree !is CrdtTree) {
            logError(TAG, "fail to execute, only Tree can execute edit")
            return ExecutionResult(opInfos = emptyList())
        }

        // For undo ops, translate the stored integer offsets back to live CrdtTreePos
        // so that reconcile adjustments are honoured.  For all other operations use
        // the stored positions directly.
        val (actualFrom, actualTo) =
            if (isUndoOp) {
                tree.indexRangeToPosRange(undoFromOffset to undoToOffset)
            } else {
                fromPos to toPos
            }

        if (!tree.checkPosRangeValid(actualFrom to actualTo)) {
            logError(TAG, "has invalid pos range, skip executing the operation")
            return ExecutionResult(opInfos = emptyList())
        }

        // For undo ops that restore deleted content, rebuild fresh CrdtTreeNodes from
        // the stored snapshots so that new IDs (derived from executedAt) avoid collisions
        // with the already-tombstoned originals.  For normal operations, use contents
        // directly (deep-copied by tree.edit as usual).
        val editContents: List<CrdtTreeNode>? =
            when {
                isUndoOp && removedNodeSnapshots != null -> {
                    buildFreshNodes(removedNodeSnapshots, executedAt)
                }
                else -> contents?.map(CrdtTreeNode::deepCopy)
            }

        val editedAt = executedAt
        val result =
            tree.edit(
                actualFrom to actualTo,
                editContents,
                splitLevel,
                editedAt,
                issueTimeTicket(editedAt),
                versionVector,
            )

        root.acc(result.dataSize)

        result.gcPairs.forEach(root::registerGCPair)

        val opInfos =
            result.changes.map {
                OperationInfo.TreeEditOpInfo(
                    it.from,
                    it.to,
                    it.fromPath,
                    it.toPath,
                    it.value?.map(TreeNode::toJsonTreeNode),
                    it.splitLevel,
                    root.createPath(parentCreatedAt),
                )
            }

        // Reverse ops are only generated for local and undo/redo operations.
        val reverseOps =
            if (source == OpSource.Local || source == OpSource.UndoRedo) {
                val fromIndex =
                    opInfos
                        .filterIsInstance<OperationInfo.TreeEditOpInfo>()
                        .firstOrNull()
                        ?.from ?: 0
                val isPureSplit =
                    splitLevel > 0 && editContents.isNullOrEmpty() && result.removedNodes.isEmpty()
                val reverseOp =
                    if (isPureSplit) {
                        toSplitReverseOperation(tree, fromIndex)
                    } else if (splitLevel == 0) {
                        toReverseOperation(
                            tree,
                            actualFrom,
                            fromIndex,
                            editContents,
                            result.removedNodes,
                            result.mergeLevel,
                        )
                    } else {
                        null
                    }
                listOfNotNull(reverseOp)
            } else {
                emptyList()
            }

        return ExecutionResult(opInfos = opInfos, reverseOps = reverseOps)
    }

    /**
     * Builds the reverse [TreeEditOperation] that undoes this operation.
     *
     * [actualFrom] is the position that was actually used as the range start
     * (valid after position refinement).
     *
     * The reverse operation:
     * - Deletes the content inserted by this operation (if any).
     * - Re-inserts any content that was deleted, stored as [TreeNode] snapshots
     *   so that fresh [CrdtTreeNodeID]s are assigned at undo-apply time.
     *
     * [undoFromOffset]/[undoToOffset] capture the document-index range so that
     * [reconcileOperation] can adjust them when concurrent remote edits arrive.
     *
     * Special case: if [redoSplitLevel] > 0, this op is a boundary-deletion
     * that undid a split. Its redo must regenerate a proper split at the
     * merge point rather than re-inserting raw tombstoned boundary nodes.
     *
     * Special case: if [mergeLevel] > 0, this op is a cross-boundary merge that
     * deleted element boundaries and moved their children into the target,
     * leaving empty shells in [removedNodes]. Re-inserting those shells would
     * nest the elements; instead the reverse is a split of [mergeLevel] levels
     * that re-creates the boundaries. Mirrors JS SDK PR #1237.
     */
    private fun toReverseOperation(
        tree: CrdtTree,
        actualFrom: CrdtTreePos,
        fromIndex: Int,
        editContents: List<CrdtTreeNode>?,
        removedNodes: List<CrdtTreeNode>,
        mergeLevel: Int = 0,
    ): TreeEditOperation {
        if (redoSplitLevel > 0) {
            val splitFromPos = tree.findPos(fromIndex)
            return TreeEditOperation(
                parentCreatedAt = parentCreatedAt,
                fromPos = splitFromPos,
                toPos = splitFromPos,
                contents = null,
                splitLevel = redoSplitLevel,
                executedAt = executedAt,
                undoFromOffset = fromIndex,
                undoToOffset = fromIndex,
            )
        }

        if (mergeLevel > 0) {
            val splitFromPos = tree.findPos(fromIndex)
            return TreeEditOperation(
                parentCreatedAt = parentCreatedAt,
                fromPos = splitFromPos,
                toPos = splitFromPos,
                contents = null,
                splitLevel = mergeLevel,
                executedAt = executedAt,
                undoFromOffset = fromIndex,
                undoToOffset = fromIndex,
            )
        }

        // Document-index span occupied by what was actually inserted. For undo
        // ops this comes from the freshly-rebuilt snapshot nodes, not the
        // original [contents] (which is null on undo ops). Each node
        // contributes its [paddedSize]: text length for text nodes, or
        // `2 + sum(children.paddedSize)` for elements (open + close + body).
        val insertedSpan = editContents?.sumOf { it.paddedSize } ?: 0

        // Integer range of the reverse op: covers the inserted span (if any).
        // fromIndex is the live-tree position just before this edit was applied.
        val reverseFromIndex = fromIndex
        val reverseToIndex = fromIndex + insertedSpan

        // Convert deleted nodes to plain TreeNode snapshots so the reverse op
        // can create fresh CrdtTreeNodes with non-conflicting IDs at apply time.
        val snapshots = removedNodes.map(CrdtTreeNode::toTreeNode).ifEmpty { null }

        return TreeEditOperation(
            parentCreatedAt = parentCreatedAt,
            fromPos = actualFrom,
            toPos = actualFrom,
            contents = null,
            splitLevel = 0,
            executedAt = executedAt,
            undoFromOffset = reverseFromIndex,
            undoToOffset = reverseToIndex,
            removedNodeSnapshots = snapshots,
        )
    }

    /**
     * Builds the reverse [TreeEditOperation] for a pure split (splitLevel > 0).
     *
     * A split creates 2*splitLevel boundary tokens (one close + one open tag
     * per level). The reverse is a boundary-deletion: a splitLevel=0 edit
     * that removes those tokens, merging the split elements back together.
     *
     * Tags [redoSplitLevel] on the returned op so that its own reverse (the
     * redo) regenerates a proper split rather than re-inserting raw boundary
     * nodes as content.
     *
     * Returns null if the boundary indices exceed the tree size (the split
     * was a no-op due to concurrent parent deletion).
     */
    private fun toSplitReverseOperation(tree: CrdtTree, preEditFromIdx: Int): TreeEditOperation? {
        val boundarySize = 2 * splitLevel
        val reverseFromIdx = preEditFromIdx
        val reverseToIdx = preEditFromIdx + boundarySize

        if (reverseToIdx > tree.size) return null

        val reverseFromPos = tree.findPos(reverseFromIdx)
        val reverseToPos = tree.findPos(reverseToIdx)

        return TreeEditOperation(
            parentCreatedAt = parentCreatedAt,
            fromPos = reverseFromPos,
            toPos = reverseToPos,
            contents = null,
            splitLevel = 0,
            executedAt = executedAt,
            undoFromOffset = reverseFromIdx,
            undoToOffset = reverseToIdx,
            redoSplitLevel = splitLevel,
        )
    }

    /**
     * Adjusts [undoFromOffset] and [undoToOffset] to account for a concurrent remote edit
     * that arrived at [[remoteFrom], [remoteTo]) inserting [remoteContentSize] nodes/chars.
     *
     * Six overlap cases (matching the JS implementation):
     * - Remote is entirely left of undo range: shift both endpoints right.
     * - Remote is entirely right of undo range: no change.
     * - Undo range is contained by remote: collapse to a point at remoteFrom.
     * - Remote is contained by undo range: expand toPos by content delta.
     * - Remote overlaps the start of undo range: shift fromPos right.
     * - Remote overlaps the end of undo range: truncate toPos.
     *
     * No-ops when [isUndoOp] is false.
     */
    internal fun reconcileOperation(
        remoteFrom: Int,
        remoteTo: Int,
        remoteContentSize: Int,
    ) {
        if (!isUndoOp) return

        val undoFrom = undoFromOffset
        val undoTo = undoToOffset
        val remoteDelta = remoteContentSize - (remoteTo - remoteFrom)

        val newUndoFrom: Int
        val newUndoTo: Int

        when {
            // Case 2: remote is entirely right of undo range — no change.
            remoteFrom >= undoTo -> return
            // Case 1: remote is entirely left of undo range — shift both endpoints.
            remoteTo <= undoFrom -> {
                newUndoFrom = undoFrom + remoteDelta
                newUndoTo = undoTo + remoteDelta
            }
            // Case 3: undo range is contained by remote — collapse to a point.
            remoteFrom <= undoFrom && remoteTo >= undoTo -> {
                newUndoFrom = remoteFrom + remoteContentSize
                newUndoTo = remoteFrom + remoteContentSize
            }
            // Case 4: remote is contained by undo range — expand toPos only.
            remoteFrom > undoFrom && remoteTo < undoTo -> {
                newUndoFrom = undoFrom
                newUndoTo = undoTo + remoteDelta
            }
            // Case 5: remote overlaps the start of undo range.
            remoteFrom <= undoFrom -> {
                newUndoFrom = remoteFrom + remoteContentSize
                newUndoTo = undoTo + remoteDelta
            }
            // Case 6: remote overlaps the end of undo range.
            else -> {
                newUndoFrom = undoFrom
                newUndoTo = remoteFrom
            }
        }

        undoFromOffset = newUndoFrom
        undoToOffset = newUndoTo
    }

    private fun issueTimeTicket(executedAt: TimeTicket): () -> TimeTicket {
        var delimiter = executedAt.delimiter
        if (contents != null) {
            delimiter += contents.size.toUInt()
        }
        return { TimeTicket(executedAt.lamport, ++delimiter, executedAt.actorID) }
    }

    companion object {
        private const val TAG = "TreeEditOperation"

        /** Sentinel value indicating this operation is not from the undo/redo stack. */
        @Suppress("ktlint:standard:property-naming")
        internal const val NotAnUndoOp = -1

        /**
         * Converts a list of [TreeNode] snapshots to fresh [CrdtTreeNode]s whose IDs
         * are derived from [executedAt]. Each node receives a unique delimiter starting
         * from [executedAt]'s current delimiter + 1; descendants receive further
         * incremented delimiters so all IDs in the rebuilt subtree are unique.
         */
        internal fun buildFreshNodes(
            snapshots: List<TreeNode>,
            executedAt: TimeTicket,
        ): List<CrdtTreeNode> {
            var delimiter = executedAt.delimiter

            fun issueTicket(): TimeTicket =
                TimeTicket(executedAt.lamport, ++delimiter, executedAt.actorID)

            fun buildNode(snapshot: TreeNode): CrdtTreeNode {
                return when (snapshot) {
                    is TreeTextNode -> {
                        CrdtTreeText(CrdtTreeNodeID(issueTicket(), 0), snapshot.value)
                    }

                    is TreeElementNode -> {
                        val ticket = issueTicket()
                        val id = CrdtTreeNodeID(ticket, 0)
                        CrdtTreeElement(
                            id,
                            snapshot.type,
                            attributes =
                            Rht().apply {
                                snapshot.attributes.forEach { (key, value) ->
                                    set(key, value, ticket)
                                }
                            },
                        ).also { node ->
                            snapshot.childNodes.forEach { child ->
                                val childNode = buildNode(child)
                                node.append(childNode)
                            }
                        }
                    }
                }
            }

            return snapshots.map(::buildNode)
        }
    }
}
